8.0 stable
rgeo/activerecord-postgis-adapter pull request #388
Opened 2023-11-12 18:03 UTC by Beardev118

## What does this PR do?
 - Fixed tests with to_s comparison

2023-11-28 18:44 UTC, keithdoggett reviewed
Thanks for submitting this @Beardev118. Like I mentioned in my comment the goal is to be able to compare objects directly and not attributes since that used to work, but isn't anymore. A good first step would be identifying which attributes are different from each other and we can then work towards identifying the issue.

2023-11-28 18:44 UTC, keithdoggett commented on test/cases/basic_test.rb
> +      assert_equal factory.point(0, 0).y, obj.default_latlon.y
I think the bigger issue we're trying to look at here is that we should be able to compare by rgeo objects and not their attributes.

```ruby
assert_equal factory.point(0,0), obj.default_latlon
```
should work but it's not for some reason.

2023-11-28 21:07 UTC, Beardev118 commented on test/cases/basic_test.rb
> +      assert_equal factory.point(0, 0).y, obj.default_latlon.y
Fixed this issue

2023-11-30 14:18 UTC, keithdoggett requested changes
Good catch thanks for looking into that. We can now apply that to the other failing test too,

2023-11-30 14:18 UTC, keithdoggett commented on test/cases/basic_test.rb
> +      assert_equal area_p, obj_area_p
We also need to change this back to comparing `area` and `object.area` directly. We can remove the `MyPolygon` class as well.

2023-11-30 16:14 UTC, Beardev118 commented on test/cases/basic_test.rb
> +      assert_equal area_p, obj_area_p
Updated

2023-11-30 18:55 UTC, Beardev118 commented
Hello, Keith
Would you please tell me how can I test the failed cases in the local?
With current test code, I can't find the failed cases in the local

2023-11-30 21:36 UTC, keithdoggett commented
It's only failing on postgres 11. I assume it has something to do with not being able to cast the WKT for the default value to the proper SRID now that it's been changed to 3857.

Thinking about this more I think the solution is to change the SRID of that column back to 0 and instead modify the `factory` method in `test_helper` to accept an srid parameter.

```ruby
def factory(srid: 3857)
      RGeo::Cartesian.preferred_factory(srid: srid)
end
```
And when we're comparing data to the `default_latlon` we do

```ruby
      assert_equal factory(srid: 0).point(0, 0), obj.default_latlon
```

2023-11-30 22:25 UTC, Beardev118 commented
All workflow passed

![image](https://github.com/rgeo/activerecord-postgis-adapter/assets/55624311/3173403a-ab54-4181-9eaf-7e6f208a14da)

2023-12-04 21:37 UTC, keithdoggett commented
Thanks @Beardev118 this looks good. Last question is any reason this is pointing to 8.0-stable rather than main?

2023-12-04 22:02 UTC, Beardev118 commented
Thank you for your response
You wrote: "In the update to version 8, a few tests have to use to_s to
compare result geometries instead of the objects directly. We should be
able to compare the objects directly, though."
So, I started with 8.0-stable branch, but it can be applied  to the main
branch
If you want, I'll edit it to the main branch


On Mon, Dec 4, 2023 at 10:37 PM Keith Doggett ***@***.***>
wrote:

> Thanks @Beardev118 <https://github.com/Beardev118> this looks good. Last
> question is any reason this is pointing to 8.0-stable rather than main?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rgeo/activerecord-postgis-adapter/pull/388#issuecomment-1839520403>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANIME564R2R6LBGLS4ZN2XDYHY7CDAVCNFSM6AAAAAA7IFIXHSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZZGUZDANBQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-04 22:07 UTC, Beardev118 reviewed
Updated

2023-12-05 23:19 UTC, merged

2023-12-05 23:19 UTC, keithdoggett commented
Thank you! LGTM merging

2023-12-06 00:04 UTC, Beardev118 commented
You're welcome!

On Wed, Dec 6, 2023 at 12:19 AM Keith Doggett ***@***.***>
wrote:

> Thank you! LGTM merging
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rgeo/activerecord-postgis-adapter/pull/388#issuecomment-1841784245>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANIME525L4CPPIQWHXA2J2LYH6TZ3AVCNFSM6AAAAAA7IFIXHSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBRG44DIMRUGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>